version: '3'
networks:
  app-tier:
    external: true

services:
  mysqldb:
    image: mysql
    hostname: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: capstone
    networks:
      - app-tier

  zookeeper:
    hostname: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

  kafka:
    hostname: kafka
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      # - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    # depends_on:
    #   - zookeeper
    networks:
      - app-tier

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysqldb
    ports:
      - 8183:80
    environment:
      MYSQL_USERNAME: admin
      MYSQL_ROOT_PASSWORD: admin
      PMA_ARBITRARY: 1
    networks:
      - app-tier

  data_ingestion:
    deploy:
      replicas: 1
    build: data_ingestion
    links:
      - mysqldb
      - kafka
    stdin_open: true
    restart: always
    tty: true
    networks:
      - app-tier


