version: '3'
networks:
  app-tier:
    external: true

services:
  preprocessor:
    build: preprocessor
    links: 
      - mysqldb
    volumes:
      - ./data:/app/data
    depends_on: 
      - mysqldb
    tty: true